# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-13
    strategy:
      matrix:
        configuration: [iOS, watchOS]
    steps:
    - uses: actions/checkout@v3
    
    - name: Set Xcode Version
      run: sudo xcode-select -s /Applications/Xcode_15.0.app
        
    - name: Archive
      env:
        deOs: ${{ matrix.configuration }}
      run: xcodebuild archive -scheme DarockKit -destination "generic/platform=${{ env.deOs }}" -archivePath "./DarockKit-${{ env.deOs }}"
  
    - name: Upload Archive
      uses: actions/upload-artifact@v3
      with:
        name: DarockKit-${{ matrix.configuration }}
        path: ./DarockKit-${{ matrix.configuration }}
          
